# Generated by Django 5.0.6 on 2025-01-11 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledgementReceipt', '0024_ticketreservation_archive_ticket_date_availed'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketreservation_archive',
            name='Gcash_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
