# Generated by Django 5.0.6 on 2025-01-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledgementReceipt', '0026_remove_ticketreservation_archive_gcash_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('DECLINED', 'Declined')], default='PENDING', max_length=20)),
                ('qr_code', models.URLField(blank=True, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
